<tr>
    <th class="b1">DETAILS                                              </th>
    <th class="b1">ID                                                   </th>
    <th class="b1">STARTDATUM                                           </th>
    <th class="b1">ABLAUFDATUM                                          </th>
    <th class="b1"><img src="/img/administration/icons/edit-16.png"  />       </th>
    <th class="b1"><img src="/img/administration/icons/delete-16.png"/>       </th>
    <th class="b1" style="width:500px"><img src="/img/administration/icons/url-16.png"   /> [URL] </th>
</tr>
