<?php
    $edit         = $this->escapeHtml($this->url('administration/infoscript/default', array('action' => 'edit'  , 'id' => $this->id)));
    $delete       = $this->escapeHtml($this->url('administration/infoscript/default', array('action' => 'delete', 'id' => $this->id)));

    $count        = $this->partialLoop()->getPartialCounter(); //every partial which belongs to a partial loop knows this

    $trStyleClass = ($count % 2) ? 'tr1' : 'tr1 grey';

?>


<tr class="<?= $trStyleClass ?>">
    <td class="b2"><a href="<?= $this->url('administration/infoscript/default', array('action' => 'detail', 'id' => $this->id)) ?>"> DETAILS</a> </td>
    <td class="b2">         <?= $this->id          ?>                                                                                                         </td>
    <td class="b2">         <?= $this->startdatum  ?>                                                                                                         </td>
    <td class="b2">         <?= $this->ablaufdatum ?>                                                                                                         </td>
    <td class="b3"><a href="<?= $edit              ?>">                 <img src="/img/administration/icons/edit-16.png"  />                                   </a> </td>
    <td class="b3"><a href="<?= $delete            ?>">                 <img src="/img/administration/icons/delete-16.png"/>                                   </a> </td>
    <td class="b4"><a href="<?= $this->url         ?>" target="_blank"> <img src="/img/administration/icons/url-16.png"   />  <?= $this->url ?>                </a> </td>
</tr>