<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FuThuer - Administration')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body style="background:url(http://subtlepatterns.com/patterns/little_pluses.png) #cacaca;">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner" style="background:url(/img/pattern/dark_brick_wall.png)">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo 'FuThuer'?> </a>
                    <div class="nav-collapse collapse">
                        <?= $this->navigation('navigation')->menu()->setMinDepth(0)->setMaxDepth(0)->setUlClass('nav'); ?>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>


        <div class="container">
            <div class="nav-collapse collapse futhuernav">
                <?= $this->navigation('navigation')->menu()->setMinDepth(0)->setMaxDepth(3);?>
            </div>


            <div style="float:left; height:100%; width: 80%;">

                <?php echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0);?>
                <?= $this->content;?>
            </div>



            <div style="float:left;width: 100%;">
            <hr>
            <footer>
                &copy; FuThuer 2013

            </footer>
            </div>
<!--            <footer>
                <p>&copy; 2005 - <?php // echo date('Y') ?> by Zend Technologies Ltd. <?php // echo $this->translate('All rights reserved.') ?></p>
            </footer>-->
        </div> <!-- /container -->
        <?= $this->inlineScript() ?>
    </body>
</html>
