<?php
    $this->headTitle('Manager - Infoscripte');

    $displayFlashMessage  = function($flashMessage){
        echo $flashMessage . "<br/>";
    };

    $tableHeadPartialPath = $this->url($this->route) .
            '/partial/infoscript/header.phtml';

    $tableBodyPartialPath = $this->url($this->route) .
            '/partial/infoscript/infoscript.phtml';

    $createUrl = $this->escapeHtml($this->url($this->route,
                           array('action' => 'create-infoscript')));

    $newIconUrl = "/img/campustv/icons/new-16.png";

?>

<style type="text/css">
    th, b1 {
        background-color: yellowgreen;
        border: 2px solid blue;
        text-align: left;
    }

    td.b2 {
        border: 1px solid blue;
        text-align: left;
    }

    td.b3 {
        border: 1px solid blue;
        text-align: center;
    }

    tr.tr1{
        border: 1px solid blue;
        text-align: left;
    }

    tr.grey {
        background-color: gainsboro;
    }

</style>



<h1>CampusTV Infoscriptmanager</h1>

<div style="background-color: #0F0; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesSuccess); ?>
</div>
<div style="background-color: #F00; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesFail); ?>
</div>
<div style="background-color: #FF0; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesInfo); ?>
</div>

Aufgaben: <a href="<?= $createUrl  ?>"> <img src= "<?= $newIconUrl ?>"/> </a>


<h2>Aktive Infoscripte</h2>
<table>
    <?= $this->partial($tableHeadPartialPath);                      ?>
    <?= $this->partialLoop($tableBodyPartialPath, $this->active);   ?>
</table>


<h2>Abgelaufene Infoscripte</h2>
<table>
    <?= $this->partial($tableHeadPartialPath);                      ?>
    <?= $this->partialLoop($tableBodyPartialPath, $this->outdated); ?>
</table>

<h2>Zukünftige Infoscripte</h2>
<table>
    <?= $this->partial($tableHeadPartialPath);                      ?>
    <?= $this->partialLoop($tableBodyPartialPath, $this->future);   ?>
</table>