-- Generated by Ora2Pg, the Oracle database Schema converter, version 11.4
-- Copyright 2000-2013 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=212.201.65.202;sid=fut1

SET client_encoding TO 'LATIN1';

\set ON_ERROR_STOP ON

CREATE TABLE tbl_partner (
	par_id bigserial NOT NULL,
	par_name varchar(100) NOT NULL,
	par_firstname varchar(100),
	par_website char(200),
	par_email varchar(100) NOT NULL,
	par_phone varchar(30),
	par_fax varchar(30),
	par_pob char(10),
	par_password varchar(32) NOT NULL,
	par_nickname varchar(100) NOT NULL,
	par_newsletter smallint,
	par_expiry timestamp,
	par_expiryinfo timestamp,
	par_lastupdate timestamp DEFAULT CURRENT_TIMESTAMP,
	par_registerinfo integer
);
ALTER TABLE tbl_partner ADD PRIMARY KEY (par_id);

CREATE TABLE aktuelle_anzeigen_new (
	id bigserial NOT NULL,
	positions_id bigint,
	anzahl_wiederholungen integer DEFAULT 0,
	anzeige_id bigint,
	news_id bigint
);
ALTER TABLE aktuelle_anzeigen_new ADD PRIMARY KEY (id);

CREATE TABLE anzeige_new (
	id bigserial NOT NULL,
	schaltungsanfang timestamp,
	schaltungsende timestamp,
	wahrscheinlichkeit smallint,
	such_id bigint,
	kunden_id bigint,
	positions_id bigint,
	imwarenkorb smallint,
	gebuchte_wochen smallint
);
ALTER TABLE anzeige_new ADD PRIMARY KEY (id);

CREATE TABLE ctv_preise (
	woche smallint NOT NULL,
	preis varchar(6) NOT NULL
);
ALTER TABLE ctv_preise ADD PRIMARY KEY (woche);

CREATE TABLE feiertage (
	id serial NOT NULL,
	bezeichnung varchar(100) NOT NULL,
	datum timestamp NOT NULL
);
ALTER TABLE feiertage ADD PRIMARY KEY (id);

CREATE TABLE standort (
	id serial NOT NULL,
	bezeichnung varchar(100) NOT NULL,
	strasse varchar(50) NOT NULL,
	plz varchar(10) NOT NULL,
	ort varchar(100) NOT NULL,
	organisations_id bigint NOT NULL
);
ALTER TABLE standort ADD PRIMARY KEY (id);

CREATE TABLE nachrichten_portale (
	id bigserial NOT NULL,
	url varchar(300) NOT NULL,
	startdatum timestamp,
	ablaufdatum timestamp
);
ALTER TABLE nachrichten_portale ADD PRIMARY KEY (id);

CREATE TABLE position (
	id int NOT NULL,
	bezeichnung varchar(100) NOT NULL,
	standort_id int NOT NULL
);
ALTER TABLE position ADD PRIMARY KEY (id);

CREATE TABLE zeitzonen (
	id serial NOT NULL,
	bezeichnung varchar(50) NOT NULL,
	standort_id int NOT NULL,
	von smallint NOT NULL,
	bis smallint NOT NULL
);
ALTER TABLE zeitzonen ADD PRIMARY KEY (id);

CREATE TABLE tbl_company (
	par_id integer NOT NULL,
	cmt_id integer NOT NULL,
	cbr_id integer NOT NULL,
	cmp_employees integer,
	cmp_locationd smallint,
	cmp_locationth smallint,
	cmp_official_email varchar(100)
);
ALTER TABLE tbl_company ADD PRIMARY KEY (par_id);
CREATE INDEX fkis ON tbl_company (cmt_id);
CREATE INDEX fkactive_in ON tbl_company (cbr_id);
CREATE TABLE tbl_address (
	adr_id serial NOT NULL,
	adr_street varchar(100) NOT NULL,
	adr_zipcode varchar(5) NOT NULL,
	adr_city varchar(100) NOT NULL,
	par_id integer NOT NULL
);
ALTER TABLE tbl_address ADD PRIMARY KEY (adr_id);
CREATE INDEX fkhas ON tbl_address (par_id);
CREATE TABLE url (
	id bigserial NOT NULL,
	url varchar(300) NOT NULL,
	pst_id integer
);
ALTER TABLE url ADD PRIMARY KEY (id);

ALTER TABLE zeitzonen ADD CONSTRAINT sys_c0045005 FOREIGN KEY (standort_id) REFERENCES standort (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE aktuelle_anzeigen_new ADD CONSTRAINT sys_c0065271 FOREIGN KEY (positions_id) REFERENCES position (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE aktuelle_anzeigen_new ADD CONSTRAINT sys_c0065272 FOREIGN KEY (anzeige_id) REFERENCES anzeige_new (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE aktuelle_anzeigen_new ADD CONSTRAINT sys_c0065273 FOREIGN KEY (news_id) REFERENCES nachrichten_portale (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE tbl_address ADD CONSTRAINT fkhas FOREIGN KEY (par_id) REFERENCES tbl_partner (par_id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE position ADD CONSTRAINT sys_c0045010 FOREIGN KEY (standort_id) REFERENCES standort (id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
