<?php
    $edit = $this->escapeHtml($this->url('administration/anzeige/default', array('action' => 'edit-anzeige', 'id' => $this->id)));
    $delete = $this->escapeHtml($this->url('administration/anzeige/default', array('action' => 'delete-anzeige', 'id' => $this->id)));

    $count = $this->partialLoop()->getPartialCounter(); //every partial which belongs to a partial loop knows this
    $trStyleClass = ($count % 2) ? 'tr1' : 'tr1 grey';
?>



<tr class="<?= $trStyleClass ?>">
    <td class="b2">         <?= $this->schaltungsanfang ?>                                                                  </td>
    <td class="b2">         <?= $this->schaltungsende   ?>                                                                  </td>
    <td class="b2">         <?= $this->gebuchte_wochen  ?>                                                                  </td>
    <td class="b2">         <?= $this->positions_id     ?>                                                                  </td>
    <td class="b3"><a href="<?= $edit                   ?>                "> <img src="/img/administration/icons/edit-16.png"  /> </a> </td>
    <td class="b3"><a href="<?= $delete                 ?>                "> <img src="/img/administration/icons/delete-16.png"/> </a> </td>
    <td class="b4"><a href="<?= $this->url              ?>" target="_blank"> <img src="/img/administration/icons/url-16.png"   /> </a> </td>
</tr>







