<?php
$count = 0;

foreach ($this->anzeigen as $a) :
    $id       = $this->escapeHtml($a['ID']);
    $start    = $this->escapeHtml($a['SCHALTUNGSANFANG']);
    $end      = $this->escapeHtml($a['SCHALTUNGSENDE']);
    $booked   = $this->escapeHtml($a['GEBUCHTE_WOCHEN']);
    $customer = $this->escapeHtml($a['PAR_NAME']);
    $display  = $this->escapeHtml($a['POSITIONS_ID']);
    $edit     = $this->escapeHtml($this->url('campustv/anzeige-manager/default', array('action' => 'edit-anzeige', 'id' => $id)));
    $delete   = $this->escapeHtml($this->url('campustv/anzeige-manager/default', array('action' => 'delete-anzeige', 'id' => $id)));
    $url      = $this->escapeHtml($a['URL']);

    ++$count;
    ?>

    <?php if ($count % 2 == 1) : //ungerade zeilen weiß lassen ?>
        <tr class="tr1">
        <?php else : //gerade zeilen mit grauem hintergrund belegen ?>
        <tr class="tr1 grey">
        <?php endif; ?>

        <td class="b2">         <?= $start ?></td>
        <td class="b2">         <?= $end ?></td>
        <td class="b2">         <?= $booked ?></td>
        <td class="b2">         <?= $customer ?></td>
        <td class="b2">         <?= $display ?></td>
        <td class="b3"><a href="<?= $edit ?>">                <img src="/img/campustv/icons/edit-16.png"/>   </a> </td>
        <td class="b3"><a href="<?= $delete ?>">              <img src="/img/campustv/icons/delete-16.png"/> </a> </td>
        <td class="b4"><a href="<?= $url ?>" target="_blank"> <img src="/img/campustv/icons/url-16.png"/>    </a> </td>
    </tr>
    <?php
endforeach;
?>