


<h1>CampusTV Manager Infoscript bearbeiten</h1>





<?php

use Campustv\Model\Entity\Infoscript as InfoscriptModel;

$form = $this->form;
$form->setAttribute('action', $this->url($this->route, array('action' => 'edit-infoscript', 'id' => $this->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('ID'));
?>

<ul>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(InfoscriptModel::TBL_COL_BEGIN_DATE))); ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(InfoscriptModel::TBL_COL_END_DATE)));   ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(InfoscriptModel::TBL_COL_URL)));        ?></li>


    <?= $this->formSubmit($form->get('submit')); ?>
</ul>

<?php echo $this->form()->closeTag(); ?>