<?php $this->headTitle('Manager - Infoscripte'); ?>

<style type="text/css">
    th, b1 {
        background-color: yellowgreen;
        border: 2px solid blue;
        text-align: left;
    }

    td.b2 {
        border: 1px solid blue;
        text-align: left;
    }

    td.b3 {
        border: 1px solid blue;
        text-align: center;
    }

    tr.tr1{
        border: 1px solid blue;
        text-align: left;
    }

    tr.grey {
        background-color: gainsboro;
    }

</style>


<?php
    $displayFlashMessage = function($flashMessage){
        echo $flashMessage . "<br/>";
    }
?>

<h1>CampusTV Infoscriptmanager</h1>

<div style="background-color: #0F0; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesSuccess); ?>
</div>
<div style="background-color: #F00; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesFail); ?>
</div>
<div style="background-color: #FF0; font-size: larger;">
    <?php array_map($displayFlashMessage, $this->flashMessagesInfo); ?>
</div>

Aufgaben: <a href="<?php echo $this->escapeHtml($this->url($this->route, array('action' => 'create-infoscript'))); ?>"><img src="/img/campustv/icons/new-16.png"/></a>


<h2>Aktive Infoscripte</h2>
<table>
    <?= $this->partial($this->url($this->route) . '/partial/infoscript/header.phtml', array()); ?>
    <?= $this->partialLoop($this->url($this->route) . '/partial/infoscript/infoscript.phtml', $this->active); ?>
</table>


<h2>Abgelaufene Infoscripte</h2>
<table>
    <?= $this->partial($this->url($this->route) . '/partial/infoscript/header.phtml', array()); ?>
    <?= $this->partialLoop($this->url($this->route) . '/partial/infoscript/infoscript.phtml', $this->outdated); ?>
</table>

<h2>Zukünftige Infoscripte</h2>
<table>
    <?= $this->partial($this->url($this->route) . '/partial/infoscript/header.phtml', array()); ?>
    <?= $this->partialLoop($this->url($this->route) . '/partial/infoscript/infoscript.phtml', $this->future); ?>
</table>