<tr>
    <th class="b1">SCHALTUNGSANFANG                                </th>
    <th class="b1">SCHALTUNGSENDE                                  </th>
    <th class="b1">WOCHEN                                          </th>
    <th class="b1" style="width:400px;">KUNDENBEZEICHNUNG                               </th>
    <th class="b1">POSITIONS_ID                                    </th>
    <th class="b1"><img src="/img/administration/icons/edit-16.png"  />  </th>
    <th class="b1"><img src="/img/administration/icons/delete-16.png"/>  </th>
    <th class="b1"><img src="/img/administration/icons/url-16.png"   />  </th>
</tr>
