
<?php $this->headTitle('Manager - Anzeige erstellen')?>

<h1>CampusTV Manager Anzeige erstellen</h1>





<?php

use CampusTV\Model\Entity\Anzeige as AnzeigeModel;

$form = $this->form;
$form->setAttribute('action', $this->url($this->route, array('action' => 'create-anzeige')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

//echo $this->formCollection($form);
?>



<ul class="form-list">
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(AnzeigeModel::TBL_COL_CUSTOMER_ID)));  ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(AnzeigeModel::TBL_COL_BEGIN_DATE)));   ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(AnzeigeModel::TBL_COL_BOOKED_WEEKS))); ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(AnzeigeModel::TBL_COL_DISPLAY_ID)));   ?></li>
    <li><?= $this->partial($this->url($this->route).'/partial/formElement.phtml',array('formElement' => $form->get(AnzeigeModel::TBL_COL_URL)));          ?></li>
</ul>


<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag(); ?>