<h2>CampusTV Anzeige Löschen</h2>


Sind Sie sicher, dass Sie die Anzeige <?php echo $anzeige->getId() ?> mit der Adresse <?php echo $anzeige->getUrl() ?> löschen möchten?

<p> </p>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('campustv/manager/default', array('action' => 'delete-anzeige', 'id' => $id)));
$form->prepare();

echo $this->form()->openTag($form);
?>

<input type="hidden" name="id" value="<?php echo (int) $anzeige->getId(); ?>" />
<input type="submit" name="del" value="ja" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<input type="submit" name="del" value="nein" />

<?php
echo $this->form()->closeTag();
?>
